Updates
jsergio123/script.module.resolveurl pull request #114
Opened 2019-05-14 00:31 UTC by jewbmx

all tested and working.

2019-05-14 07:58 UTC, cache-sk commented
Note - don't forget to bump plugin version in addon.xml.. :)

2019-05-14 08:11 UTC, jewbmx commented
I leave that kinda stuff to the main dev.

2019-05-14 22:37 UTC, jsergio123 requested changes
you have errors in your PR

2019-05-14 22:45 UTC, jsergio123 requested changes

2019-05-14 22:45 UTC, jsergio123 commented on lib/resolveurl/plugins/tunepk.py
> +                    sources.append((vids[key]['label'], vids[key]['file']))
issue here

2019-05-14 22:45 UTC, jsergio123 commented on lib/resolveurl/plugins/veoh.py
> +        _data = json.loads(_json)
wrap in try/else please

2019-05-14 23:00 UTC, jewbmx commented
Both those are cache-sk's fixes, think both are exact copies from the pastebins

2019-05-15 08:41 UTC, cache-sk commented
Sorry guys for making this mess, created separate pull #115

2019-05-15 15:33 UTC, jewbmx commented
No worries, if the rest of my pr is good, jsergio can accept it first and then accept yours right afterwards to apply the rest of your fix.

2019-05-16 22:25 UTC, closed without merging