cda fix
jsergio123/script.module.resolveurl pull request #324
Opened 2020-04-08 17:36 UTC by grzebzi

fixed url collection, must delete 4 chars from the end of decoded string

2020-04-09 02:23 UTC, Gujal00 requested changes

2020-04-09 02:23 UTC, Gujal00 commented on lib/resolveurl/plugins/cda.py
> +        a=a[:-4]
Are you sure that this line is required? I can't see any slice instance in the javascript code

2020-04-09 02:23 UTC, Gujal00 commented on lib/resolveurl/plugins/cda.py
>          strurl = strurl if strurl.startswith('http') else 'https://{0}'.format(strurl)
this line is now redundant

2020-04-09 02:23 UTC, Gujal00 commented on lib/resolveurl/plugins/cda.py
>          strurl = strurl if strurl.endswith('.mp4') else '{0}.mp4'.format(strurl)
This line is also redundant

2020-04-09 02:23 UTC, Gujal00 commented on lib/resolveurl/plugins/cda.py
> +        a = a.replace("0)sss.mp4", ".mp4")
Are you sure that this line is required? I can't see any replace instance in the javascript code

2020-04-09 05:02 UTC, Gujal00 commented
Thanks for the PR. I have cherry picked the changes and adapted it
https://github.com/jsergio123/script.module.resolveurl/commit/c50789551a350f812da05ddfc9180422475685a8

2020-04-09 05:02 UTC, closed without merging

2020-04-09 14:58 UTC, grzebzi commented
Thanks, 
slice is required, I've compared result address and the actual file streamed in browser.
Not sure about replace, that might be some old stuff.

I expect CDA to change coding frequently.

2020-04-12 22:56 UTC, Gujal00 commented
@grzebzi 
As suspected it is not a slice and hence is broken in current release
I located the logic and it could be 3 or 4 or 5 characters  replaced. The fixed version is in the git now. WIll be included in the next release