Fix settings file saving on kodi 19
jsergio123/script.module.resolveurl pull request #348
Opened 2020-06-27 10:52 UTC by host505

I got errors such as
```
Error Type: <class 'UnicodeEncodeError'>
Error Contents: 'charmap' codec can't encode characters in position 155-166: character maps to <undefined>
Traceback (most recent call last):
 File "C:\Users\xxx\Desktop\Kodi 19\Kodi\portable_data\addons\script.module.resolveurl\lib\default.py", line 20, in <module>
   from resolveurl.lib import kodi
 File "C:\Users\xxx\Desktop\Kodi 19\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 320, in <module>
   _update_settings_xml()
 File "C:\Users\xxx\Desktop\Kodi 19\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 313, in _update_settings_xml
   f.write(new_xml)
 File "C:\Users\xxx\Desktop\Kodi 19\Kodi\system\python\Lib\encodings\cp1252.py", line 19, in encode
   return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 155-166: character maps to <undefined>
```

when trying to save settings or perform actions such as 'reset function cache', while on kodi 19 and interface language other than english.
This still works with older kodi versions.

2020-06-28 23:28 UTC, Gujal00 requested changes
Unfortunately this breaks Python 2 as there is no encoding option for open in Python2 so errors on Kodi 18 and below. Need to rethink with maybe using six to handle this

2020-06-29 02:39 UTC, Gujal00 commented
Thanks for the report and working out the fix for 19.
I have redone the fix taking both PY2 and PY3 into consideration using six module. in https://github.com/jsergio123/script.module.resolveurl/commit/72a34c5f87881b3922adc629fc7fe0c8e3f35992
Please have a look if it solves your issue.
I am closing this PR

2020-06-29 02:39 UTC, closed without merging

2020-06-29 09:47 UTC, host505 commented
> Unfortunately this breaks Python 2 as there is no encoding option for open in Python2 so errors on Kodi 18 and below.

You're right about py2, I tested with kodi 18 and it worked, but I forgot that 18 has a python 3 interpreter as well.
On kodi 17 it gives errors indeed.

2020-07-15 12:48 UTC, host505 commented
Hi, I'm bringing this back up because there seems a problem has occurred since the recent changes; there seems to be a problem with kodi 18 this time (Greek kodi lang):
https://i.imgur.com/SnSbWqt.png
The problem seems to be [line 312](https://github.com/jsergio123/script.module.resolveurl/blob/master/lib/resolveurl/__init__.py#L312), I think the right thing to use here is `six.ensure_text()` instead of `six.u()` - at least that's what is working on my end (tested on k18 & k19, Greek & English kodi ui)

2020-07-15 23:53 UTC, Gujal00 commented
Yes it looks like `six.ensure_text()` is better in this scenario, will change it for the next release