fix
jsergio123/script.module.resolveurl pull request #362
Opened 2020-08-16 03:07 UTC by anis3

2020-08-20 23:10 UTC, Gujal00 requested changes

2020-08-20 23:10 UTC, Gujal00 commented on lib/resolveurl/plugins/anistream.py
> +            html = base64.b64decode(r.group(1)).decode('utf-8')
Please test this in Kodi 19 as the current code will cause issue in Python3
specifically the decode and base64 have to be handled correctly for Python3

2020-08-20 23:10 UTC, Gujal00 commented on lib/resolveurl/plugins/anistream.py
> +import re, base64
Please follow FLAKE8 standards, one import per line

2020-08-20 23:10 UTC, Gujal00 commented on lib/resolveurl/plugins/anistream.py
> +    Copyright (C) 2020 gujal
you can add your name for the copyright :-)

2020-08-21 06:49 UTC, anis3 commented
I have tested it with kodi 18 (win10 & android) & 19(win10) works

2020-08-22 01:22 UTC, Gujal00 approved these changes

2020-08-22 01:22 UTC, merged