fix upstream
jsergio123/script.module.resolveurl pull request #378
Opened 2020-09-26 14:08 UTC by anis3

2020-09-27 00:07 UTC, Gujal00 requested changes

2020-09-27 00:07 UTC, Gujal00 commented on lib/resolveurl/plugins/upstream.py
> +    Copyright (C) 2020 Anis3
Add your name along with any earlier developer with a comma

2020-09-27 00:07 UTC, Gujal00 commented on lib/resolveurl/plugins/upstream.py
> +                                     generic_patterns=False)
You need to add `referer=False` as well, otherwise you will get "embed restricted to domain" errors on some embeds similar to gounlimited

2020-09-29 18:18 UTC, anis3 commented
satisfied now ???
if not, please do as you think

if what would I complain

work kodi 18,19

2020-09-29 22:31 UTC, Gujal00 commented
Thanks

2020-09-29 22:31 UTC, merged