Streamtape additional domain
jsergio123/script.module.resolveurl pull request #555
Opened 2021-11-21 12:09 UTC by host505

2021-11-21 17:40 UTC, host505 commented
Sorry, wrong pattern regex. Can you help, I'm not good at it.

2021-11-21 21:23 UTC, jewbmx commented
I use what jsergio tossed me a while back... https://regex101.com/r/6sjcce/1
Page should load to a perfect example of what your doin too 😉

2021-11-21 21:24 UTC, Gujal00 requested changes

2021-11-21 21:24 UTC, Gujal00 commented on lib/resolveurl/plugins/streamtape.py
> +    pattern = r'(?://|\.)(str(?:eam|cloud)?tap?e?\.(?:com|cloud|net|pe|site|link))/(?:e|v)/([0-9a-zA-Z]+)'
pattern = r'(?://|\.)(str(?:eam)?(?:tap?e?|cloud)\.(?:com|cloud|net|pe|site|link))/(?:e|v)/([0-9a-zA-Z]+)'

2021-11-22 06:29 UTC, host505 commented on lib/resolveurl/plugins/streamtape.py
> +    pattern = r'(?://|\.)(str(?:eam|cloud)?tap?e?\.(?:com|cloud|net|pe|site|link))/(?:e|v)/([0-9a-zA-Z]+)'
Done, thx

2021-11-22 20:03 UTC, Gujal00 approved these changes

2021-11-22 20:03 UTC, Gujal00 commented
Thanks

2021-11-22 20:04 UTC, merged

2022-02-04 21:22 UTC, Gujal00 commented
@host505 can you please start using `https://github.com/Gujal00/ResolveURL`
I wont be looking into this repo anymore. Thanks